services:
  fnos-qbit-proxy:
    image: fnos-qb-proxy:arm64
    container_name: fnOS-qBit-Proxy
    pid: "host"
    network_mode: "bridge"
    environment:
      - PASSWORD=fnosnb
      - PORT=8086
    ports:
      - "7777:8086"
    volumes:
      # 挂载有效 sock 路径：宿主机的 /usr/trim/var/downloadcenter/1000/qbt.sock → 容器内同路径
      - /usr/trim/var/downloadcenter/1000/qbt.sock:/usr/trim/var/downloadcenter/1000/qbt.sock
    restart: unless-stopped
